### ISSUE TITLE
EPERM error

### ISSUE THREAD

**Issue by yoFra** [pierrefourgeaud/node-single-instance#1]
Bonjour Pierre,
J'utilise single-instance pour mon projet. Merci pour ton développement.

J'ai l'erreur suivante qui provient de mon appli lancée soit sous root soit sous un autre user.
Je voudrais proposer à l'utilisateur de le lancer en sudo au cas où l'erreur apparait.
Mais voilà, je n'arrive pas à catcher cette erreur :

home/pi/domoticz/plugins/DomoticzTuya/node_modules/single-instance/index.js:42
          throw e;
          ^

Error: EPERM: operation not permitted, unlink '/tmp/DomoticzTuyaInterface.sock'
    at Object.unlinkSync (fs.js:1053:3)
    at Socket.<anonymous> (/home/pi/domoticz/plugins/DomoticzTuya/node_modules/single-instance/index.js:39:12)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -1,
  syscall: 'unlink',
  code: 'EPERM',
  path: '/tmp/DomoticzTuyaInterface.sock'
}

Mon bout de code :
```javascript
    // single instance app
    // On veut se protéger : ne lancer qu'un seul manager même si Domoticz en demande plusieurs
    try {
        var locker = new SingleInstance('DomoticzTuyaInterface');
        locker.lock()
            .then(function() { 
                // console on socket
                const sl = new socklogger();
                // start manager
                Manager.Start(mgrPort); 
            })
            .catch(function(err) {
                if ( err.code == 'EPERM' )
                    console.log('Try 1 : sudo ', process.argv[1], ' [<listeningPort>]');
                else
                    console.log('toto>>>>>>>>>>>>> ', err);
                process.exit(2);
            })
    }
    catch (err) {
        if ( err.code == 'EPERM' )
            console.log('Try 2 : sudo ', process.argv[1], ' [<listeningPort>]');
    }
```

PS/ Je ne suis pas un grand spécialiste du JS. Je m'y suis mis avec le confinement Covid :(

**Comment by yoFra** [comment]
Je te propose la modification suivante en lignes 41-43 d'index.js :

```javascript
        if (e.code !== 'ENOENT') {
          // Don't throw any error
          //throw e;
          // But reject
          reject(e);
        }
```

Mon bout de code devient :

```javascript
    // single instance app
    // On veut se protéger : ne lancer qu'un seul manager même si Domoticz en demande plusieurs
    var locker = new SingleInstance('DomoticzTuyaInterface');
    locker.lock()
        // Pour le 1er qui sera le seul à fonctionner :
        .then ( function() { 
            // console on socket
            const toto = new socklogger();
            // start tuya device manager
            Manager.Start(process.argv[2]); 
        })
        // Tous les autres passeront par ici :
        .catch ( function(err) {
            if ( err.code == 'EPERM' )
                console.log('No permission, try : sudo ', process.argv[1], ' [<listeningPort>]');
            else
                console.log('>>>>>>>>>>>>>>>>', err);
            process.exit(126);
        })
```

**Comment by manibharathytu** [comment]
I'm facing the same error. I'm using sudo to overcome it. 
 
Looking for a better solution.

**Comment by yoFra** [comment]
Hi Mani bharathy,

If you find, could you tell me.

Thanks.           .YO.

**Comment by manibharathytu** [comment]
Sure. Now I'm using this piece of code which does the same. 

`var net = require('net');

var isPortInUse = function(port, callback) {
    var server = net.createServer(function(socket) {
	socket.write('Echo server\r\n');
	socket.pipe(socket);
    });

    server.listen(port, '127.0.0.1');
    server.on('error', function (e) {
	callback(true);
    });
    server.on('listening', function (e) {
	// server.close();
	callback(false);
    });
};


isPortInUse(5858, function(portInUse) {
    if (portInUse) {
    console.log("An instance already running");
    process.exit()
    }`
